---
- name: Prepare
  hosts: all
  gather_facts: false
  vars:
     facts: "{{ lookup('file', molecule_instance_config) | from_yaml }}"
     ansible_ssh_private_key_file: '{{ facts[0].identity_file }}'
  tasks:
    - shell: curl -sSL https://repos-droplet.digitalocean.com/install.sh | bash
    - shell: curl -sSL https://repos.insights.digitalocean.com/install.sh | bash
    - name: Install python for Ansible
      package:
         name: python3, python3-pip
      become: true
